# Cấu hình ngưỡng cho các bài tập
squat:
  # Các góc quan trọng dùng để đo chiều sâu hoặc trạng thái
  critical_angles:
    - [23, 25, 27] # Left Hip, Knee, Ankle
    - [24, 26, 28] # Right Hip, Knee, Ankle
  # Ngưỡng (Threshold)
  depth_threshold_angle: 100 # Góc gối nhỏ hơn 100 độ thì được tính là đủ sâu
  rom_threshold_signal: 0.5 # Biến thiên tín hiệu (PCA PC1) tối thiểu so với min/max

push_up:
  critical_angles:
    - [11, 13, 15] # Left Shoulder, Elbow, Wrist
    - [12, 14, 16] # Right Shoulder, Elbow, Wrist
  depth_threshold_angle: 90
  rom_threshold_signal: 0.5

# Cấu hình chung cho thuật toán
fsm:
  max_hold_time_frames: 150 # Nếu pause quá 5s (150 frames @ 30fps) thì huỷ rep
  velocity_epsilon: 0.002 # Giảm từ 0.05 xuống 0.002 để phát hiện chuyển động dễ hơn

dtw:
  window_size: 15 # Sakoe-Chiba band radius
